# This file was generated by the {rix} R package v0.15.5 on 2025-11-13
# with following call:
# >rix::rix(r_ver = "b4799c4e2ab67607399726b3d2406cfe0f58997c",
#  > r_pkgs = c("broom",
#  > "broom.helpers",
#  > "cardx",
#  > "ggplot2",
#  > "ggsci",
#  > "ggsignif",
#  > "ggsurvfit",
#  > "gitignore",
#  > "gt",
#  > "gtsummary",
#  > "here",
#  > "janitor",
#  > "parameters",
#  > "rix",
#  > "survival",
#  > "tidyverse",
#  > "visdat"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision b4799c4e2ab67607399726b3d2406cfe0f58997c for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/b4799c4e2ab67607399726b3d2406cfe0f58997c.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      broom
      broom_helpers
      cardx
      ggplot2
      ggsci
      ggsignif
      ggsurvfit
      gitignore
      gt
      gtsummary
      here
      janitor
      parameters
      rix
      survival
      tidyverse
      visdat;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      positron-bin
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  
}
