# This file was generated by the {rix} R package v0.16.0 on 2025-11-15
# with following call:
# >rix::rix(r_ver = "79177b2ec0687dca919b4cf719a6aa56e1c0ef96",
#  > r_pkgs = c("broom",
#  > "broom.helpers",
#  > "cardx",
#  > "ggplot2",
#  > "ggsci",
#  > "ggsignif",
#  > "ggsurvfit",
#  > "gitignore",
#  > "gt",
#  > "gtsummary",
#  > "here",
#  > "janitor",
#  > "parameters",
#  > "rix",
#  > "survival",
#  > "tidyverse",
#  > "visdat",
#  > "webshot2"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision 79177b2ec0687dca919b4cf719a6aa56e1c0ef96 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/79177b2ec0687dca919b4cf719a6aa56e1c0ef96.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      broom
      broom_helpers
      cardx
      ggplot2
      ggsci
      ggsignif
      ggsurvfit
      gitignore
      gt
      gtsummary
      here
      janitor
      parameters
      rix
      survival
      tidyverse
      visdat
      webshot2;
  };
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      positron-bin
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [  rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
