rix::rix(
         project_path = ".",
         r_ver = "latest-upstream",
         r_pkgs = c(
           "broom",
           "broom.helpers",
           "cardx",
           "ggplot2",
           "ggsci",
           "ggsignif",
           "ggsurvfit",
           "gitignore",
           "gt",
           "gtsummary",
           "here",
           "janitor",
           "parameters",
           "rix",
           "survival",
           "tidyverse",
           "visdat",
           "webshot2"
         ),
         ide = "positron",
         system_pkgs = NULL,
         git_pkgs = NULL,
         overwrite = TRUE,
)
